export const DEFAULTS = {
  model: "big-cock",
  theme: "system",
  providers: {},
  models: {},
  mcp: {
    "khazai-code": { type: "builtin", builtin: "code" },
  },
  web: {
    allowPrivate: false,
    search: { providers: null },
  },
  toolTimeout: 60000,
  providerTimeout: 300000,
  reasoningEffort: "medium",
  permission: {},
  lsp: false,
  defaultAgent: "build",
  subagentConcurrency: 3,
  system: "You are Khazai, a professional coding agent. Never mention your underlying model name (MiMo, Xiaomi, etc). Your name is Khazai or Big Cock. Always respond as Khazai.",
  maxTurns: 200,
  tokenBudget: 24000,
  contextLimit: null,
  compactThreshold: 0.9,
  apiKey: "",
};
