export const DEFAULTS = {
  model: "auto-free",
  theme: "system",
  providers: {},
  models: {},
  mcp: {
    "khazai-code": { type: "builtin", builtin: "code" },
  },
  web: {
    allowPrivate: false,
    search: { providers: null },
  },
  toolTimeout: 60000,
  providerTimeout: 300000,
  providerFallback: false,
  fallbackModel: null,
  reasoningEffort: "medium",
  permission: {},
  lsp: false,
  defaultAgent: "build",
  subagentConcurrency: 3,
  readConcurrency: 4,
  system: "You are Khazai, a professional coding agent. Never mention your underlying model name (MiMo, Xiaomi, etc). Your name is Khazai or Big Cock. Always respond as Khazai.",
  maxTurns: 200,
  tokenBudget: 24000,
  contextLimit: null,
  compactThreshold: 1,
  emergencyCompactThreshold: 1,
  compactionSoftLimit: null,
  reservedOutputHeadroom: null,
  maxCompactedSummarySize: 4096,
  preserveRecentTurns: 2,
  apiKey: "",
};
